name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message/reason'
        required: true
        default: 'QA approved - deploying to production'
        type: string

permissions:
  contents: read

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test-repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest

      - name: Display deployment info
        run: |
          echo "=========================================="
          echo "Manual Deployment to Production"
          echo "=========================================="
          echo "Message: ${{ inputs.deploy_message }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Deploying to: prod-repo"
          echo "=========================================="

      - name: Clone prod-repo
        env:
          PAT_TOKEN: ${{ secrets.PROD_REPO_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Verify PAT token exists
          if [ -z "$PAT_TOKEN" ]; then
            echo "Error: PROD_REPO_PAT secret is not set!"
            exit 1
          fi

          # Clone using PAT
          git clone https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository_owner }}/prod-repo.git prod-repo-temp

          if [ $? -ne 0 ]; then
            echo "Error: Failed to clone prod-repo. Check PAT permissions."
            exit 1
          fi

      - name: Copy files to prod-repo
        run: |
          # Copy all files except .git and prod-repo-temp
          rsync -av --exclude='prod-repo-temp' --exclude='.git' --exclude='.github' --exclude='node_modules' . prod-repo-temp/

      - name: Commit and push to prod-repo
        env:
          PAT_TOKEN: ${{ secrets.PROD_REPO_PAT }}
        run: |
          cd prod-repo-temp

          # Configure git to use PAT for push
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository_owner }}/prod-repo.git

          git add .

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy from test-repo: ${{ inputs.deploy_message }} (by ${{ github.actor }})"
            git push origin main

            if [ $? -ne 0 ]; then
              echo "Error: Failed to push to prod-repo. Check PAT permissions."
              exit 1
            fi
          fi

      - name: Deployment summary
        run: |
          echo "✅ Successfully deployed to prod-repo!"
          echo "Deployment message: ${{ inputs.deploy_message }}"
          echo "Triggered by: ${{ github.actor }}"
