name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message/reason'
        required: true
        default: 'QA approved - deploying to production'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Display deployment info
      run: |
        echo "=========================================="
        echo "Manual Deployment to Production"
        echo "=========================================="
        echo "Message: ${{ inputs.deploy_message }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Deploying from: test-repo/main"
        echo "Deploying to: prod-repo/main"
        echo "=========================================="

    - name: Push to prod-repo using PAT
      env:
        PAT_TOKEN: ${{ secrets.PROD_REPO_PAT }}
      run: |
        # Configure git
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

        # Push to prod-repo using PAT in URL
        git remote add prod-repo https://oauth2:${PAT_TOKEN}@github.com/Ali-ISAA/prod-repo.git
        git push prod-repo main --force

    - name: Deployment summary
      run: |
        echo "✅ Successfully deployed to prod-repo!"
        echo "Deployment message: ${{ inputs.deploy_message }}"
        echo "Triggered by: ${{ github.actor }}"
